name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Docker 이미지 빌드
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 2. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 도커이미지 빌드하고 허브로 푸쉬
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: . # 현재 디렉토리를 컨텍스트로 사용
          push: true # 이미지를 푸시할 것인지 설정
          platforms: linux/amd64 # 타겟 플랫폼
          tags: ${{ secrets.DOCKERHUB_REPOSITORY }}

# Reference: https://github.com/docker/build-push-action
